pipeline {
    agent any

    environment {
        GIT_URL = "https://github.com/PraveenKuberABC/Amazon-Ecom.git"
        BRANCH  = "master"
    }

    stages {

        stage('Clone Repository') {
            steps {
                echo "Cloning Code..."
                git url: "${GIT_URL}", branch: "${BRANCH}"
            }
        }

        stage('Clean') {
            steps {
                echo "Cleaning previous build..."
                sh "mvn clean"
            }
        }

        stage('Compile') {
            steps {
                echo "Compiling source code..."
                sh "mvn compile"
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                sh "mvn test"
            }
        }

        stage('Build') {
            steps {
                echo "Building package..."
                sh "mvn package"
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying application..."
                echo "This is just a placeholder deploy step!"
            }
        }
    }

    post {
        success { echo " SUCCESS: Pipeline completed successfully!" }
        failure { echo " ERROR: Pipeline failed!" }
        always  { echo " DONE: Pipeline finished (success or failure)." }
    }
}







A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
B
B
B
B
B
B

